In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[2,3,4], [1,6,5]])
print(b)

[[2 3 4]
 [1 6 5]]


In [4]:
print(a+b)

[[3 5 7]
 [2 8 8]]


In [5]:
# Get dimentions
a.ndim
# b.ndim

1

In [6]:
# 1D-> (columns)
# 2D-> (rows, columns)
# 3D -> ...
b.shape

(2, 3)

In [7]:
# Get type
a.dtype

dtype('int16')

In [17]:
# Get size of one element
a.itemsize

# Get size of array (number of elements)
a.size

# Get size of whole array (in bytes)
print(a.itemsize * a.size)
# a.nbytes

6


In [24]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
c[:, -1]

array([ 7, 14])

In [32]:
# Create matrix with zero's
matrix0 = np.zeros([5,5])

matrix0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
# Create matrix with ones's
matrix1 = np.ones((2,2))
matrix1

array([[1., 1.],
       [1., 1.]])

In [40]:
# Create matrix with specified number
matrixn = np.full((3,2), 69, dtype='float32')
matrixn

array([[69., 69.],
       [69., 69.],
       [69., 69.]], dtype=float32)

In [44]:
matrix_like = np.full_like(c, 9)
matrix_like


array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])