In [1]:
import numpy as np

In [27]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [16]:
b = np.array([[2,3,4], [1,6,5]])
print(b)

[[2 3 4]
 [1 6 5]]


In [29]:
print(a+b)

[[3 5 7]
 [2 8 8]]


In [24]:
# Get dimentions
a.ndim
# b.ndim

1

In [25]:
# 1D-> (columns)
# 2D-> (rows, columns)
# 3D -> ...
b.shape

(2, 3)

In [32]:
# Get type
a.dtype

dtype('int16')

In [37]:
# Get size
a.itemsize

2