In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[2,3,4], [1,6,5]])
print(b)

[[2 3 4]
 [1 6 5]]


In [4]:
print(a+b)

[[3 5 7]
 [2 8 8]]


In [5]:
# Get dimentions
a.ndim
# b.ndim

1

In [6]:
# 1D-> (columns)
# 2D-> (rows, columns)
# 3D -> ...
b.shape

(2, 3)

In [7]:
# Get type
a.dtype

dtype('int16')

In [17]:
# Get size of one element
a.itemsize

# Get size of array (number of elements)
a.size

# Get size of whole array (in bytes)
print(a.itemsize * a.size)
# a.nbytes

6


In [24]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
c[:, -1]

array([ 7, 14])

In [32]:
# Create matrix with zero's
matrix0 = np.zeros([5,5])

matrix0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
# Create matrix with ones's
matrix1 = np.ones((2,2))
matrix1

array([[1., 1.],
       [1., 1.]])

In [40]:
# Create matrix with specified number
matrixn = np.full((3,2), 69, dtype='float32')
matrixn

array([[69., 69.],
       [69., 69.],
       [69., 69.]], dtype=float32)

In [44]:
matrix_like = np.full_like(c, 9)
matrix_like


array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [70]:
np.random.rand(4,2)

array([[0.92507803, 0.69553979],
       [0.78077651, 0.01459276],
       [0.80441889, 0.67815705],
       [0.69076997, 0.78092473]])

In [62]:
np.random.randint(5, size=(3,3))

array([[2, 0, 1],
       [1, 3, 4],
       [1, 1, 0]])

In [73]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [83]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [92]:
r1 = np.ones(5)
r1
r2 = np.array([1,0,0,0,1])
r3 = np.array([1,0,9,0,1])
r3
arr = np.array([r1,r2,r3,r2,r1])
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
r1 = np.ones((5,5))
r1[1:4, 1:4] = np.zeros((3,3))
r1[2][2]=9
r1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# How to copy arrays. Very important!!!
a = np.array([1,2,3])
b = a.copy()
b[0]=100
print(a)

[1 2 3]


In [24]:
# Multiplication matricies
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [29]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0