In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.13.0


In [9]:
x = tf.constant(4)
print(x)
x = tf.constant([1,2,3.2])
print(x)
x = tf.constant([[1,2,3], [4,2,5]])
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1.  2.  3.2], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 2 5]], shape=(2, 3), dtype=int32)


In [14]:
x = tf.constant(5, shape=(1,1), dtype=tf.float32)
print(x)
x = tf.ones((2,2))
print(x)
x = tf.eye(3) # Identity matrix (eye)
print(x)

tf.Tensor([[5.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [19]:
x = tf.random.normal((3,3), mean = 0, stddev=1)
print(x)
x = tf.random.uniform((1,3), minval=1.5, maxval=2.)
print(x)
x = tf.range(9)
print(x)

tf.Tensor(
[[ 0.9261874  -0.49729228 -1.368099  ]
 [ 0.10183173 -2.4018764   0.15819077]
 [-0.13775055 -0.8077075  -2.3742843 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[1.6268699 1.8825505 1.7728912]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [20]:
x = tf.constant([3.2, 5.8], dtype=tf.float32)
x = tf.cast(x, dtype=tf.int32)
print(x)

tf.Tensor([3 5], shape=(2,), dtype=int32)


In [23]:
x = tf.constant([3,2,5])
y = tf.constant([6,9,-2])

# z = tf.add(x, y)
z = x + y
print(z)

z = tf.tensordot(x, y, axes=1) # Sum the product of elements
print(z)
z = tf.reduce_sum(x*y, axis=0)
print(z)


tf.Tensor([ 9 11  3], shape=(3,), dtype=int32)
tf.Tensor(26, shape=(), dtype=int32)
tf.Tensor(26, shape=(), dtype=int32)


In [24]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[-0.2160643  -1.0107305   0.9886828  -1.2741518 ]
 [-0.06779549 -1.535405    1.8934791  -1.3736275 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.2160643  -1.0107305   0.9886828  -1.2741518 ]
 [-0.06779549 -1.535405    1.8934791  -1.3736275 ]], shape=(2, 4), dtype=float32)


In [25]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x[0,:])
print(x[:,0])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [29]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [32]:
x = tf.transpose(x, perm=[1,0]) # change the axis
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
